block-types:
  - '1:0=5'
messages:
  1: '&cЛимитирование блоков с типом {block} установленно на {limit}'
  2: '&cИзвините, у вас недостаточно прав, чтобы использовать данную команду.'
  3:
    - '&7Использование: &c/{command} <add/remove/list> <type:data> <limit>'
  4: '&7Количество зарегистрированных блоков: &e{size}&7.'
  5: '&7Блок &c{block}&7 был зарегистрирован с лимитом в &e{limit} &7блоков.'
  6: '&7Блок &c{block}&7 был удалён.'
permission-use: 'prison.magicchunk'